steps:

- name: 'gcr.io/concrete-crow-244606/sonar-scanner:latest'
  args:
    - '-Dsonar.host.url=http://35.238.209.220:9000'
    - '-Dsonar.login=84ab78a95139a8d3679613ef3f82ef4f1e66c0aa'
    - '-Dsonar.projectKey=javademoapp'
    - '-Dsonar.sources=./src/user/'
  
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install']
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/concrete-crow-244606/javademoappwithcloudbuild', '.']
  
artifacts:
  objects:
    paths: ['/workspace/target/DemoPipelineJava-0.0.1-SNAPSHOT.war']
    
images: ['gcr.io/concrete-crow-244606/javademoappwithcloudbuild']
