steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install']
- name: 'gcr.io/cloud-builders/docker'
  args: ['ls -lart']
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull','tomcat']
- name: 'gcr.io/cloud-builders/docker'
  args: ['run','tomcat']
