steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/sodium-sublime-243008/javademoappwithcloudbuild:$SHORT_SHA', '.']
artifacts:
  objects:
    location: 'gs://ganeshbucketdel7may/javademoapp'
    paths: ['/workspace/target/DemoPipelineJava-0.0.1-SNAPSHOT.war']
images: ['gcr.io/lexical-list-227517/javademoappwithcloudbuild:$SHORT_SHA']
