steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['clean', 'install']
artifacts:
  objects:
    location: 'gs://mybucket/'
    paths: ['test.war']
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'tomcat']
