steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['clean', 'install']
artifacts:
  objects:
    location: 'gs://ganeshbucketdel7may/javademoapp'
    paths: ['/workspace/target/DemoPipelineJava-0.0.1-SNAPSHOT.war']
